django/helloworld/urls.py
"""三种写法：
   1.path只能绝对匹配路径地址，不支持正则匹配。匹配规则是RoutePattern
   2.re_path支持正则匹配，django 1.x版本常用。匹配规则是RegexPattern
   3.url支持正则匹配，实际上就是return re_path, django2.x版本推荐
   url是部分动态
   页面有分页情况时，不能写死。可通过正则\d+ 匹配
   例：url('^demo/page=\d+$', views.demo)
"""
# # 默认demo
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import re_path, path
from . import view
from hello import views
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'cards', views.CardViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^accounts/login/', views.login),
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.index),
    url(r'^test$', view.test),
    url(r'^$', views.index),
    url(r'^demo', views.demo, name="demo_page"),
    url(r'^home$', views.home, name="home_page"),
    url('^demo/page=(\d+)$', views.page),
    path("archive/<year>/<month>.html", views.home1),   # 获取url参数，匹配 archive/2018/10.html
    url(r'^archive1/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2}).html$', views.home2),  # 通过正则匹配url, archive1/2018/10.html
    path("yoyo/", views.yoyo),
    path("page1/", views.page1),
    path("sonpage/", views.sonpage),
    path("get_demo/", views.get_demo),
    url(r'^qq/', views.test_qq),
    url(r'^result/', views.result_qq),
    url(r'^user/', views.user),
    url(r'^register/', views.register),  # 新增用户
    url(r'^reset/', views.reset_psw),
]

django/hello/models.py
from django.db import models

# Create your models here.
# 我们新建了一个Person类，继承自models.Model,
class Person(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    def __str__(self):
        return self.__doc__ + ":name>" + self.name

# 新增一张用户表，表名为user 字段user_name, psw ,mail 都是字符串类型
class User(models.Model):
    user_name = models.CharField(max_length=30,
                                 primary_key=True)   # 设置为主键
    psw = models.CharField(max_length=30)
    mail = models.CharField(max_length=30)
    def __str__(self):
        return self.__doc__ + ":user_name->" + self.user_name


class Article(models.Model):
    """文章"""
    title = models.CharField(max_length=30)  # 标题
    body = models.TextField()  # 正文
    auth = models.CharField(max_length=10)  # 作者
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    update_time = models.DateTimeField(auto_now=True)  # 最后更新时间
    def __str__(self):
        return self.__doc__ + "title->" + self.title


class Card(models.Model):
    '''银行卡 基本信息 '''
    ID = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    card_id = models.CharField(max_length=30, verbose_name="卡号", default="")
    card_user = models.CharField(max_length=10, verbose_name="姓名", default="")
    add_time = models.DateField(auto_now=True, verbose_name="添加时间")

    class Meta:
        verbose_name_plural = '银行卡账户'
        verbose_name = "银行卡账户_基本信息"

    def __str__(self):
        return self.card_id

django/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

django/hello/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<section>
    <h1>顶部导航</h1>
    <p>python自动化-基础网页</p>
    <hr>
</section>
<section>
    <h1>body正文</h1>
    <p>正文内容</p>
</section>
<section>
    <br><br><br><br><hr>
    <h1>底部导航</h1>
    <p>底部一些友情链接啊，网站导航，版权啊——基础网页</p>
</section>
</body>
</html>

django/hello/templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>demo样式</title>
</head>
<body>

<p>
    <h4> 这是我的博客地址，可以百度搜：上海-悠悠 </h4>
    <a href="https://www.cnblogs.com/yoyoketang/" target="_blank" >上海-悠悠-博客园</a>
    <hr>
    <h4> 《python自动化框架pytest》 </h4>
    <p>pytest是最强大最好用的python自动化框架，没有之一。本书详细讲解pytest框架使用方法，fixture功能是pytest的精髓，书中有详细的案例讲解。<br>
        另外最后会有项目实战代码，灵活用到selenium自动化项目上。<br>
        pytest交流群874033608

    </p>
    <a href="https://yuedu.baidu.com/ebook/902224ab27fff705cc1755270722192e4536582b" target="_blank" >百度阅读地址点此</a>
</p>

</body>
</html>

django/hello/templates/end.html
<section>
    <br><br><br><br><hr>
    <h1>底部导航</h1>
    <p>底部一些友情链接啊，网站导航，版权啊</p>
</section>

django/hello/templates/get_demo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>测试你的QQ号</title>
</head>
<body>
<p>请输入你的QQ号</p>

<form action="/result" method="get">
    qq: <input type="text" name="q"> <br>
    <br>
    <input type="submit" value="提交">
</form>

</body>
</html>

django/hello/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上海-悠悠</title>
    <base href="http://127.0.0.1:8080/" target="_blank">
</head>
<body>
<p>欢迎来到django!
    <br>
    <br>
    <a href="{% url 'demo_page' %}">跳转到demo页面</a>
</p>
</body>
</html>

django/hello/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
<h1>欢迎登录！</h1>
<form action="./index/" method="POST">
    {% csrf_token %}
      <p>
        用户名：<input type="text" id="id_username" name="username", required="required"> *
      </p>
      <p>
         密码：<input type="text" id="id_password" name="password", required="required"> *
    </p>

    <p>
          <input type="submit" value="登录">
    </p>
</form>

</body>
</html>

django/hello/templates/motherpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>母模板</title>
</head>
<body>
<section>
    <h1>顶部导航</h1>
    <p>python自动化-父类页</p>
    <hr>
</section>

<!--这是一段注释。block是一个块标签， content是标签名称-->
{% block content %} {% endblock content %}

<p>---------自动化教程---------</p>


<!--这是一段注释。block是一个块标签, ad是标签名称-->
{% block ad1 %} {% endblock ad1 %}


<section>
    <br><br><br><br><hr>
    <h1>底部导航</h1>
    <p>底部一些友情链接啊，网站导航，版权啊——父类页</p>
</section>
</body>
</html>

django/hello/templates/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询mail</title>
</head>
<body>
<form action="" method="get">
    输入用户名: <input type="text" name="name"> <br>


    <br>
    <input type="submit" value="提交">
</form>

<p>查询结果：{{email}} </p>
</body>
</html>

django/hello/templates/page1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% include 'top.html' %}
<section>
    <h1>body正文</h1>
    <p>正文内容</p>
</section>
{% include 'end.html' %}

</body>
</html>

django/hello/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
<h1>新用户注册！</h1>
<form action="" method="post">
    {% csrf_token %}
      <p>
        用户名：<input type="text" id="id_username" name="username", required="required"> * {{rename}}
      </p>
      <p>
         密码：<input type="text" id="id_password" name="password", required="required"> *
    </p>
   <p>
         注册邮箱：<input type="text" id="id_email" name="mail">
    </p>
    <p>
          <input type="submit" value="注册">
    </p>
</form>

</body>
</html>

django/hello/templates/reset_psw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>密码修改页面</title>
</head>
<body>
<h1>修改密码！</h1>
<form action="" method="post">
    {% csrf_token %}
      <p>
        用户名：<input type="text" id="id_username" name="username", required="required">*
      </p>
      <p>
         密码：<input type="password" id="id_psw" name="password", required="required">*
    </p>
   <p>
         新密码：<input type="password" id="id_new" name="new", required="required">*
    </p>
    <p>{{ msg }}</p>
    <p>
          <input type="submit" value="确定">
    </p>


</form>

</body>
</html>

django/hello/templates/sonpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>子页面</title>
</head>
<body>

<!--这是一段注释。extends继承basepage.html页面-->
{% extends "motherpage.html" %}

{% block content %}
    <p>这里是content块的填充内容</p>
{% endblock content %}

{% block ad1 %}
<ul>自动化内容</ul>
    {% for i in ads %}
    <li>{{i}}</li>
     {% endfor %}
{% endblock ad1 %}

</body>
</html>

django/hello/templates/top.html
<section>
    <h1>顶部导航</h1>
    <p>python自动化-{{location}}-{{name}}</p>
    <hr>
</section>

django/hello/templates/yoyo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上海-悠悠</title>
</head>
<body>

<h1>hello world! {{name}}同学</h1>

</body>
</html>